trigger:
  branches:
    include:
    - build19

pool:
  name: jldeenlinux
steps:
- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'settings.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(system.defaultworkingdirectory)'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '**/*.xml'
    TargetFolder: '$(system.defaultworkingdirectory)'

- task: Docker@2
  displayName: 'Docker build/push'
  inputs:
    containerRegistry: jdk8sacr
    repository: build19
  continueOnError: true

- task: HelmInstaller@0
  displayName: 'Install Helm 2.13.1'
  inputs:
    helmVersion: 2.13.1

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    command: package
    chartPath: 'charts/spring-boot-websocket-chat-demo'
    chartVersion: '$(build.BuildId)'
    destination: $(system.defaultworkingdirectory)

- task: CopyFiles@2
  displayName: 'copy helm chart'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.tgz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/charts'

- task: CopyFiles@2
  displayName: 'copy jar'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/maven'

- task: PublishBuildArtifacts@1
  displayName: 'Publish helm chart'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/charts'
    ArtifactName: charts

- task: PublishBuildArtifacts@1
  displayName: 'Publish jar'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/maven'
    ArtifactName: maven

- bash: 'rm $(system.defaultworkingdirectory)/settings.xml && echo "Successfully removed settings.xml from your default working directory."'
  displayName: 'Cleanup secure files'
