# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
imagePullSecrets: jdk8s
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi
ingress:
  enabled: true
  hostname: chattybot.k8s.az.jessicadeen.com
  annotations:
    #  kubernetes.io/ingress.class: nginx
     kubernetes.io/ingress.class: addon-http-application-routing
     cert-manager.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
  tls: true
applicationInsights:
  InstrumentationKey: 004d8eb9-d9af-49d0-bdda-b2d070eb1157
